tap "saulpw/vd"


brew "bat"
brew "btop"  # nicer version of top
brew "cheat"
brew "cmatrix"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "dua-cli"  # fast and interactive du
brew "eza"  # modern alternative to ls
brew "f2"  # batch renaming tool
brew "fd"  # friendlier find
brew "ffmpeg"
brew "figlet"
brew "findutils"
brew "fish"  # fish shell
brew "fzf"
brew "git"
brew "gitui"  # blazing fast terminal-ui for git
brew "graphicsmagick"
brew "hub"
brew "ipfs"
brew "jq"
brew "logrotate", restart_service: true
brew "massren"
brew "mosh"
brew "mpv"
brew "mtr"
brew "ncdu"
brew "ncmpcpp"
brew "pipes-sh"
brew "ranger"
brew "reattach-to-user-namespace"
brew "rename"
brew "resvg"  # svg rendering for yazi
brew "ripgrep"  # grep replacement
brew "saulpw/vd/visidata"
brew "shellcheck"
brew "ssh-copy-id"
brew "starship"  # nice looking prompts
brew "switchaudio-osx"
brew "syncthing", restart_service: true
brew "tor", restart_service: true
brew "trash"
brew "tree"  # visual output of a file tree
brew "watch"
brew "yazi"  # blazing fast terminal file manager
brew "zellij"  # terminal multiplexer and workspace with plugins
brew "zoxide"


# Casks
cask "aldente"  # menu bar tool to limit maximum charging percentage
cask "antinote"  # simple scratchpad for quick notes
cask "appcleaner"
cask "betterdisplay"  # fine control of displays and create virtual displays
cask "bitwarden"  # password manager
cask "choosy"
cask "chromedriver"
cask "cleanshot"
cask "discord"
cask "disk-inventory-x"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "font-victor-mono"
cask "font-victor-mono-nerd-font"  # victor mono with nerd font additions
cask "ghostty"
cask "google-chrome"
cask "gpg-suite"
cask "granola"  # ai note taking for meetings
cask "hazel"  # automate actions on files
cask "hiddenbar"  # menu bar item hiding
cask "imageoptim"
cask "keycastr"  # displays key presses for screen presentations
cask "losslesscut"
cask "macvim-app"
cask "mediainfo"
cask "mpv"
cask "obs"
cask "obsidian"
cask "plex"
cask "plexamp"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "raycast"
cask "rustdesk"  # virtual/remote desktop
cask "signal"
cask "spotify"
cask "steam"
cask "steermouse"
cask "tailscale"  # private vpn network
cask "transmit"
cask "vivaldi"
