#!/usr/bin/env bash

# Check for Homebrew,
# Install if we don't have it
if ! hash brew 2>/dev/null; then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update homebrew recipes
brew update

# Make sure git is installed
brew install git

brew install coreutils
brew install findutils
brew install bash
brew install zsh

# Install these
binaries=(
  ag
  cheat
  ctags
  diff-so-fancy # better git diffs
  ffmpeg
  fzf # fuzzy searching
  graphicsmagick
  heroku
  htop
  hub
  jq # json parsing
  jrnl # journaling
  macvim
  md5sha1sum
  mobile-shell # formerly 'mosh'
  mpc
  mpd
  mpv # best video player
  mtr # network debugging
  ncdu # better disk usage
  ncmpcpp # music player
  node
  ranger # cli file tree explorer
  reattach-to-user-namespace
  rename
  rtv # cli reddit
  shellcheck
  ssh-copy-id
  tig
  tmux
  vim
  watch
  wget
  youtube-dl
)

echo "Installing binaries..."
brew install ${binaries[@]}

echo "Cleaning up..."
brew cleanup


fonts=(
  font-envy-code-r
  font-fira-code
  font-inconsolata
)

echo "Tapping the fonts keg..."
brew tap homebrew/cask-fonts

echo "Installing fonts..."
brew cask install ${fonts[@]}


apps=(
  1password
  adobe-creative-cloud
  alfred
  appcleaner
  atext
  bartender
  cathode
  dash
  disk-inventory-x
  docker
  dropbox
  evernote
  fantastical
  firefox
  google-chrome
  gpg-suite
  imagealpha
  imageoptim
  istat-menus
  keepingyouawake
  kensington-trackball-works
  keybase
  kitty
  launchcontrol
  malwarebytes
  mediainfo
  monodraw
  netspot
  oversight
  qlimagesize
  qlmarkdown
  qlstephen
  qlvideo
  quicklook-json
  qutebrowser
  slack
  spotify
  steam
  the-unarchiver
  transmit
  tripmode
  tunnelblick
  xld
)

# Install apps to /Applications
echo "Install apps..."
brew cask install ${apps[@]}

echo "Cleaning up..."
brew cleanup
