return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      indent = { enable = true },
      highlight = { enable = true },
      folds = { enable = true },
      ensure_installed = {
        'bash',
        'css',
        'csv',
        'diff',
        'fish',
        'gitcommit',
        'gitignore',
        'go',
        'helm',
        'html',
        'javascript',
        'json',
        'kitty',
        'lua',
        'markdown',
        'markdown_inline',
        'nginx',
        'python',
        'query',
        'regex',
        'ruby',
        'rust',
        'terraform',
        'tmux',
        'toml',
        'tsx',
        'typescript',
        'vim',
        'xml',
        'yaml',
        'zsh',
      },
    },
  },
}
