// Auto-generated by moshi-hook. Update with care.
import { createConnection } from "node:net"
import { homedir } from "node:os"
import { join as pathJoin } from "node:path"
import type { Plugin } from "@opencode-ai/plugin"

// Kept for debug / manual invocation. Routine events go straight to the
// daemon's Unix socket (see resolveSocketPath) — no subprocess spawn.
const helperBinary = "/opt/homebrew/bin/moshi-hook"

// Mirrors internal/config.SocketPath. The MOSHI_SOCKET_PATH override wins
// over the per-platform default so tests and dev daemons can point us at a
// throwaway socket.
function resolveSocketPath(): string {
  const override = process.env.MOSHI_SOCKET_PATH
  if (override) return override
  if (process.platform === "darwin") {
    return pathJoin(homedir(), "Library", "Application Support", "Moshi", "moshi-hook.sock")
  }
  if (process.env.XDG_RUNTIME_DIR) {
    return pathJoin(process.env.XDG_RUNTIME_DIR, "moshi-hook.sock")
  }
  return "/tmp/moshi-hook.sock"
}

interface DaemonResponse {
  type?: string
  decision?: string
  error?: string
}

// One-message-per-connection wire protocol (see internal/socket/server.go):
// dial, write one envelope as a JSON line, optionally read one response,
// close. Errors and timeouts resolve to null so callers degrade gracefully:
// fire-and-forget drops silently, permission.ask falls through to OpenCode's
// default handling.
function sendEnvelope(
  envelope: Record<string, unknown>,
  opts: { wait: boolean; waitTimeoutMs?: number },
): Promise<DaemonResponse | null> {
  return new Promise((resolve) => {
    let settled = false
    const finish = (val: DaemonResponse | null) => {
      if (settled) return
      settled = true
      try {
        sock.destroy()
      } catch {}
      resolve(val)
    }

    const sock = createConnection({ path: resolveSocketPath() })
    sock.setNoDelay(true)
    sock.once("error", () => finish(null))

    if (opts.wait && opts.waitTimeoutMs) {
      setTimeout(() => finish(null), opts.waitTimeoutMs).unref?.()
    }

    sock.once("connect", () => {
      sock.write(JSON.stringify(envelope) + "\n")
      if (!opts.wait) {
        // Fire-and-forget: half-close once the bytes are queued. The daemon
        // still acks but we don't read it; "close" wakes us up.
        sock.end()
      }
    })

    if (!opts.wait) {
      sock.once("close", () => finish(null))
      return
    }

    const chunks: Buffer[] = []
    sock.on("data", (b: Buffer) => chunks.push(b))
    const parse = () => {
      if (settled) return
      const text = Buffer.concat(chunks).toString("utf8").trim()
      if (!text) return finish(null)
      try {
        finish(JSON.parse(text.split("\n")[0]) as DaemonResponse)
      } catch {
        finish(null)
      }
    }
    sock.once("end", parse)
    sock.once("close", parse)
  })
}

function projectNameFromCwd(cwd: string | undefined): string {
  if (!cwd) return ""
  const trimmed = cwd.replace(/\/+$/, "")
  const idx = trimmed.lastIndexOf("/")
  return idx >= 0 ? trimmed.slice(idx + 1) : trimmed
}

function prettyToolName(toolName: string) {
  switch (toolName) {
    case "bash":
      return "Bash"
    case "edit":
      return "Edit"
    case "write":
      return "Write"
    case "webfetch":
      return "WebFetch"
    case "websearch":
    case "codesearch":
      return "WebSearch"
    case "task":
      return "Task"
    default:
      return toolName
  }
}

// Mirrors internal/cli/hook.go newSessionID — 16 hex chars, used when
// OpenCode hands us an event with no sessionID (rare but possible on
// initialisation paths).
function newSessionID(): string {
  const buf = new Uint8Array(8)
  crypto.getRandomValues(buf)
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("")
}

function subtitleForPermission(name: string): string {
  switch (name) {
    case "bash":
      return "Waiting for command approval"
    case "edit":
      return "Waiting for file edit approval"
    case "external_directory":
      return "Waiting for directory access approval"
    default:
      return "Waiting for approval"
  }
}

function summarizePermission(permission: Record<string, unknown>): string {
  const rawPatterns = permission.patterns
  const patterns: string[] = Array.isArray(rawPatterns)
    ? rawPatterns.filter((p): p is string => typeof p === "string" && p.length > 0)
    : []
  const name = typeof permission.permission === "string" ? permission.permission : ""
  if (patterns.length === 0) {
    return name ? name + " permission requested" : "Permission requested"
  }
  return name + ": " + patterns[0]
}

function sendSessionUpdate(
  eventName: string,
  sessionID: string | undefined,
  directory: string,
  toolName?: string,
): void {
  void sendEnvelope(
    {
      type: "session.update",
      source: "opencode",
      sessionId: sessionID || newSessionID(),
      eventName,
      cwd: directory,
      projectName: projectNameFromCwd(directory),
      toolName: toolName ?? "",
      title: "OpenCode session",
      requestedAt: new Date().toISOString(),
    },
    { wait: false },
  )
}

const server: Plugin = async ({ directory }) => ({
  event: async ({ event }) => {
    switch (event.type) {
      case "session.idle":
        sendSessionUpdate("session.idle", event.properties.sessionID, directory)
        break
      case "permission.replied":
        sendSessionUpdate("permission.replied", event.properties.sessionID, directory)
        break
      case "permission.updated":
        sendSessionUpdate("permission.updated", event.properties.sessionID, directory)
        break
      default:
        break
    }
  },
  "tool.execute.before": async (input) => {
    sendSessionUpdate("tool.execute.before", input.sessionID, directory, prettyToolName(input.tool))
  },
  "tool.execute.after": async (input) => {
    sendSessionUpdate("tool.execute.after", input.sessionID, directory, prettyToolName(input.tool))
  },
  "permission.ask": async (input, output) => {
    const actionID = typeof (input as Record<string, unknown>).id === "string"
      ? ((input as Record<string, unknown>).id as string)
      : ""
    if (!actionID) return // No id → can't correlate a response.

    const permissionName = typeof (input as Record<string, unknown>).permission === "string"
      ? ((input as Record<string, unknown>).permission as string)
      : "permission"

    // Match the daemon-side LocalApprovalTimeout (5m), plus a small buffer
    // so the round-trip wins the race against our own timer.
    const expiresAt = new Date(Date.now() + 5 * 60_000).toISOString()
    const result = await sendEnvelope(
      {
        type: "approval.request",
        source: "opencode",
        sessionId: input.sessionID || newSessionID(),
        actionId: actionID,
        eventName: "permission.ask",
        phase: "waitingForApproval",
        category: "approval_required",
        cwd: directory,
        projectName: projectNameFromCwd(directory),
        toolName: permissionName,
        title: "OpenCode permission",
        subtitle: subtitleForPermission(permissionName),
        message: summarizePermission(input as Record<string, unknown>),
        expiresAt,
        requestedAt: new Date().toISOString(),
      },
      { wait: true, waitTimeoutMs: 5 * 60_000 + 5_000 },
    )

    switch (result?.decision) {
      case "approve":
        output.status = "allow"
        break
      case "deny":
        output.status = "deny"
        break
      default:
        break
    }
  },
})

export default {
  id: "moshi-hooks",
  server,
}
